## Chapter 1

##  Vectors, Matrices, and Arrays.

### 1.0 Introduction

NumPy is the foundation of the Python machine learning stack. NumPy allows for
efficient operations on the data structures often used in machine learning: vectors,
matrices, and tensors

### 1.1 Creating a Vector

#### Problem

You need to create a vector

In [1]:
#load numpy library
import numpy as np

# Create a vector as a row
row=np.array([1,2,3])
row

array([1, 2, 3])

In [2]:
# Create a vector as a column
column=np.array([[1],
                 [2],
                 [3],
                 [4]])
column

array([[1],
       [2],
       [3],
       [4]])

In [3]:
row.shape

(3,)

In [4]:
column.shape

(4, 1)

In [5]:
# Checking the data type of array
print(type(row))
print(type(column))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### Check Number of Dimention

In [6]:
print(row.ndim)
print(column.ndim)

1
2


NumPy’s main data structure is the multidimensional array.

### 1.2 Creating a Matrix

#### Problem

You need to create a matrix.

In [7]:
import numpy as np

#create matrix
matrix=np.array([[1,2],
                 [1,3],
                 [1,4]])
print(matrix)
matrix

[[1 2]
 [1 3]
 [1 4]]


array([[1, 2],
       [1, 3],
       [1, 4]])

In [8]:
print(matrix.ndim)

2


NumPy actually has a dedicated matrix data structure:

In [9]:
matrix_object=np.mat([[1,2],
                      [1,3],
                      [1,5]])
print(matrix_object)

[[1 2]
 [1 3]
 [1 5]]


In [10]:
matrix_object

matrix([[1, 2],
        [1, 3],
        [1, 5]])

In [11]:
#Dimension Check
print(matrix_object.ndim)

2


### 1.3 Creating a Sparse Matrix

#### Problem

Given data with very few nonzero values, you want to efficiently represent it.

In [12]:
import numpy as np
from scipy import sparse
from scipy.sparse import csc_matrix

#create matrix
matrix=np.array([[0,0],
                 [0,1],
                 [3,0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse=sparse.csr_matrix(matrix)
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [13]:
# view sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [14]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

matrix_large_sparse

<3x10 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [15]:
# View original sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [16]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


### 1.4 Selected Elements

#### Problem

You need to select one or more elements in a vector or matrix.

In [17]:
import numpy as np

row_vector=np.array([1,2,3,4,5,6])

matrix=np.array([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])
# select the third element of row_vector
print(row_vector[2])

# Select second row, second column
print(matrix[1][1])

3
5


In [18]:
# Select all elements of a row vector
row_vector[:]

array([1, 2, 3, 4, 5, 6])

In [19]:
# Select everything up to and including the third element
row_vector[:3]

array([1, 2, 3])

In [20]:
# Select everything after the third element
row_vector[3:]

array([4, 5, 6])

In [21]:
# Select the last element
row_vector[-1]

6

In [22]:
# Select the first two rows and all columns of a matrix
matrix[:2,:] #[row,col]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

### 1.5 Describing a Matrix

#### Problem

You want to describe the shape, size, and dimensions of the matrix.

In [24]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

 #View number of rows and columns
matrix.shape

(3, 4)

In [25]:
# View number of elements (rows * columns
matrix.size

12

In [26]:
# View number of dimensions
matrix.ndim

2

### 1.6 Applying Operations to Elements

#### Problem

You want to apply some function to multiple elements in an array

In [2]:
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Create function that adds 100 to something
add_100=lambda i:i+100

# Create vectorized function
vectorized_add_100=np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [3]:
# Add 100 to all elements
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### 1.7 Finding the Maximum and Minimum Values

#### Problem

You need to find the maximum or minimum value in an array

In [4]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [5]:
# Return minimum element
np.min(matrix)

1

In [6]:
# find maximum element in each column
np.max(matrix,axis=0)

array([7, 8, 9])

In [7]:

# find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [8]:
# find minimum element in each column
np.min(matrix,axis=0)

array([1, 2, 3])

In [11]:
# find minumum element in each row
np.min(matrix, axis=1)

array([1, 4, 7])

### 1.8 Calculating the Average, Variance, and Standard Deviation

#### Problem

You want to calculate some descriptive statistics about an array

In [12]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

#Return mean
np.mean(matrix)

5.0

In [13]:
# Return variance
np.var(matrix)

6.666666666666667

In [14]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [15]:
# Find the mean value in each column
np.mean(matrix,axis=0)

array([4., 5., 6.])

In [16]:
np.var(matrix,axis=0)

array([6., 6., 6.])

### 1.9 Reshaping Arrays

#### Problem

You want to change the shape (number of rows and columns) of an array without changing the element values.

In [17]:
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
matrix.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [19]:
matrix.size

12

In [20]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [21]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [23]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 1.10 Transposing a Vector or Matrix

#### Problem

You need to transpose a vector or matrix.

In [24]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [26]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
# Tranpose column
np.array([[1],
          [2],
          [3],
          [4],
          [5]]).T

array([[1, 2, 3, 4, 5]])

### 1.11 Flattening a Matrix

#### Problem

You need to transform a matrix into a one-dimensional array.

In [30]:
import numpy as np

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

#Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 1.12 Finding the Rank of a Matrix

#### Problem

You need to know the rank of a matrix

In [34]:
#Use NumPy’s linear algebra method matrix_rank:
import numpy as np

matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])

#Return matrix rank
np.linalg.matrix_rank(matrix)

2

### 1.13 Calculating the Determinant

#### Problem

You need to know the determinant of a matrix

In [35]:
# Use NumPy’s linear algebra method det:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

### 1.14 Getting the Diagonal of a Matrix

#### Problem

You need to get the diagonal elements of matrix.

In [36]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [37]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [38]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

### 1.15 Calculating the Trace of a Matrix

#### Problem

You need to calculate the trace of a matrix

In [39]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

#Return trace
matrix.trace() #1+4+9

14

In [40]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

### 1.16 Finding Eigenvalues and Eigenvectors

#### Problem

You need to find the eigenvalues and eigenvectors of a square matrix.

In [41]:
# Use NumPy’s linalg.eig:
import numpy as np

matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors=np.linalg.eig(matrix)

eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [42]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

### 1.17 Calculating Dot Products

#### Problem

You need to calculate the dot product of two vectors.

In [44]:
import numpy as np

#Create two vector
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])

# Calculate dot product
np.dot(vector_a,vector_b)# 1*4+2*5+3*6

32

In [45]:
# in Python 3.5+ we can use the new @ operator:
vector_a @ vector_b

32

### 1.18 Adding and Subtracting Matrices

#### Problem

You want to add or subtract two matrices

In [46]:
import numpy as np

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [47]:
# Subtract two matrices
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

Alternatively, we can simply use the + and - operators:

In [48]:
# Add two matrices
matrix_a+matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [49]:
# Subtract two matrices
matrix_a-matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

### 1.19 Multiplying Matrices

#### Problem

You want to multiply two matrices.

In [50]:
import numpy as np

matrix_a = np.array([[1, 1],
                     [1, 2]])

matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

In [52]:
#Alternatively, in Python 3.5+ we can use the @ operator:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [53]:
# Multiply two matrices element-wise
matrix_a*matrix_b

array([[1, 3],
       [1, 4]])

### 1.20 Inverting a Matrix

#### Problem

You want to calculate the inverse of a square matrix.

In [54]:
import numpy as np

matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix) # AA(−1) = I

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [55]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

### 1.21 Generating Random Values

#### Problem
You want to generate pseudorandom values.

In [56]:
import numpy as np

#Set seed
np.random.seed(0)

In [57]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [61]:
# Generate three random integers between 1 and 1
np.random.randint(0,11,3)

array([7, 6, 8])

In [62]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-0.10321885,  0.4105985 ,  0.14404357])

In [63]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 0.27387744,  2.52093742, -2.57088231])

In [64]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.0871293 , 1.0202184 , 1.83261985])